#!/bin/bash

# This script is used to close down the mongodb port and restart services 

export PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION=false
pm2 restart parse-server --update-env

pm2 save

# Ensure PM2 restarts on reboot
sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $(whoami) --hp $(echo $HOME)

# Modify UFW rules to close mongo port after changes are done
sudo ufw delete allow $MONGO_PORT
sudo ufw reload
